blank_issues_enabled: false
contact_links:
  - name: General Databricks questions
    url: https://help.databricks.com/
    about: Issues related to Databricks and not related to the MCP servers in this repo

  - name: MCP Documentation
    url: https://databrickslabs.github.io/mcp/
    about: Documentation about MCP
